### ISSUE TITLE
TO DO 

### ISSUE THREAD

**Issue by jgacuca567** [jgacuca567/mqsecurity#2]
## TO DO
@Jaslee1 
1. <del>Gather Web Assets - For the projects completed, if its jpegs, save them in a folder and send them to me. Also include text for projects. </del>
2. <del>Include color Scheme</del>
3. <del>Create Mockup of Website in Photoshop.</del>
4. <del>Create Favicon for MQ Security</del>
5. <del>Select Fonts from Google or Typekit that will be used for MQSecurity</del>

**Comment by Jaslee1** [comment]
The selected font is Myriad Pro Regular and Myriad Pro Bold.
